### ISSUE TITLE
Syntax not appearing when using sp-marked

### ISSUE THREAD

**Issue by Scalahansolo** [gadicc/meteor-SyntaxHighlighter#2]
When running the extended string through sp-marked all of my code are getting the proper class tags it seems. Ie. `<code class="lang-js">` but all of the code on the html page is just the same color. It doesnt seem like any css is being applied to the code at all. Any idea why?

**Comment by gadicc** [comment]
No, that sounds odd.  Can you tell me if:
1. In the code block, does the `<code>` tag have a child element tag like `<div id="highlighter_123337" class="syntaxhighlighter  ">`?
2. If you view-source on a page in your Meteor project, there should be a link to a minified CSS stylesheet in the head.  In that head, if you search for `.syntaxhighlighter` are all the rules there?

**Comment by Scalahansolo** [comment]
Sorry for the late response. While fiddling around with this yesterday I figured it out. I had the `marked` package installed along with `sp-marked`. As soon as I removed `marked` it worked just fine. Maybe throw this in the README as it was not completely obvious to me?
